### ISSUE TITLE
params dict

### ISSUE THREAD

**Issue by Sum02dean** [WillKoehrsen/hyperparameter-optimization#4]
Hello! 

Thank you for the great guide and such a cool tool. 
I am a little confused about how to create the params dictionary. I.e. do I just initialize the param values once by calling sample() e.g.  in the example below i have called the sample() function within the namespace of the objective function. I assume then that fmin() will deal with subsequent assignments for each param... or am I thinking about this wrong?

Code:
```
def objective(params = sample(space)):
    """Objective function for AE Hyperparameter Optimization"""
    
    # Keep track of evals
    global ITERATION
    
    ITERATION += 1
    
    #generate parameters
    
    # Make sure parameters that need to be integers are integers
    for parameter_name in ['batch_size']:
        params[parameter_name] = int(params[parameter_name])
    
    start = timer()
    
    # run AE with pre-defined k-fold reps
    out, autoencoder, encoder, decoder =  functionalModel(data=train_ctr.X, batch_size=params['batch_size'], epochs=100, dr=params['dropout'], reg=params['regularization'], lr=params['learning_rate'], optimizer='rmsprop')
    run_time = timer() - start
    
    # Extract the best score (MSE)
    best_score = best_loss = out.history['loss'][-1]
    
    # Loss must be minimized
    loss = best_score

    # Write to the csv file ('a' means append)
    of_connection = open(out_file, 'a')
    writer = csv.writer(of_connection)
    writer.writerow([loss, params, ITERATION, run_time])
    
    # Dictionary with information for evaluation
    return {'loss': loss, 'params': params, 'iteration': ITERATION,
            'train_time': run_time, 'status': STATUS_OK}

#run fmin
from hyperopt import fmin
# Global variable
global  ITERATION

#initialize iteration to 0
ITERATION = 0
#max number of runs of algorithm
MAX_EVALS = 5

# Run optimization
best = fmin(fn = objective, space = space, algo = tpe.suggest, 
            max_evals = MAX_EVALS, trials = bayes_trials, rstate = np.random.RandomState(50))
```

I ask this before running, as I anticipate long run times, and your response may come back before my own troubleshooting. 

Thanks!

**Comment by WillKoehrsen** [comment]
Hello,

Your objective function should be run once with each set of parameters. You
don't need to sample from the search space since Hyperopt does that for
you. Define your function to take as a parameter a dictionary of
parameters, and hyperopt will sample from the parameter space and send the
parameters to the objective function. The purpose of the objective function
is to evaluate the set of hyperparameters and fmin will find the values
yielding the lowest score on the objective function.

If you are still confused, check out the Hyperopt example.
<https://github.com/hyperopt/hyperopt/wiki/FMin> You may also find the full
documentation useful. <http://hyperopt.github.io/hyperopt/>
Best,
Will

**Comment by Sum02dean** [comment]
Hi Will 
Thank you for the prompt feedback. Yes this makes sense to me now.
cheers, 

Dean

**Comment by WillKoehrsen** [comment]
Glad I could help! Best of luck on your project.
